### ISSUE TITLE
listRecordings broken

### ISSUE THREAD

**Issue by qgeissmann** [BioAcoustica/bioacousticaR#11]
`bioacoustica.listRecordings()` raises: 
```
 Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input 
```
This is likely because http://bio.acousti.ca/R/recordings/ is empty.

**Comment by edwbaker** [comment]
Should now be fixed. Note that some recordings will not have a taxon name.

**Comment by qgeissmann** [comment]
ok it works now,  cheers,
