### ISSUE TITLE
redundant `taxon` variable?

### ISSUE THREAD

**Issue by qgeissmann** [BioAcoustica/bioacousticaR#13]
The field of `R/recordings/` are: `"id","taxon","file"`. 
Does this mean recordings already have one (I presume unique) allocated taxon? 
If they have a unique taxon, why do we ask users to give a taxon variable when filling an annotation form?

I guess soundscape recordings cannot generally have a single "taxon".  Then, what is the expected value of `R/recordings$taxon` in the case of multi-species recordings?

**Comment by edwbaker** [comment]
Recordings can specify their taxon/taxa. There are a number of recordings with vague taxon indications, often at the family level (e.g. Cicadidae). The annotation function lets people indicate their identifications of these taxa.

**Comment by qgeissmann** [comment]
ok, it makes sense... so taxon can simply be an empty string for recordings...
