### ISSUE TITLE
some annotations have missing fields

### ISSUE THREAD

**Issue by qgeissmann** [BioAcoustica/bioacousticaR#4]
e.g. 

``` R
query <- bioacoustica:::getAllAnnotationData()
query[start == "", .(id, author, date, taxon)]
```

Gives:

```
 id          author             date taxon
1: 195 Scratchpad Team 2016-10-12 12:50      
2: 170      cicadasong 2016-03-19 21:08
```

No taxon, start and end time. @edwbaker should we force all annotations to have at least  start and end?
For the R frontend, I will simply exclude incomplete ones for now. This will allow me to treat start and end as numerical variables.

**Comment by edwbaker** [comment]
These should now be hidden in the data coming from the site too,

**Comment by qgeissmann** [comment]
fixed upstream
