### ISSUE TITLE
Annotation files are one second offset compared to expect value

### ISSUE THREAD

**Issue by hjosullivan** [BioAcoustica/bioacousticaR#6]
This comes from `unit = "second"` argument in `readWave()`. as implicitly `from = 1`.

**Comment by qgeissmann** [comment]
Thanks for that @hjosullivan. I will just use unit=sample and work in sample instead of second. 
This issue should also be accounted for in other project (e.g. orthophonia). 
It is a bit counter intuitive that from has default of 1  when `unit="second"`!

**Comment by qgeissmann** [comment]
fixed. closing. we also have unittest to check that now
