### ISSUE TITLE
Uploading annotations and files

### ISSUE THREAD

**Issue by qgeissmann** [BioAcoustica/bioacousticaR#8]
What is the vision for pushing annotations and files on bioacoustica from the R package?

* What sort of scenario do we imagine?
* What are the security concerns (what happens if someone uploads Terabytes of irrelevant data -- i.e. by mistake)
* Should we have a way to record whether files/annotations where uploaded "manually" vs "computationally"?
* What sort of check do we have in the backend to reject incorrect annotations /files (e.g. annotations where `start > end` cannot be correct, files that cannot be read as audio are incorrect.....)

**Comment by qgeissmann** [comment]
It seems like this should be a back-end feature to bash-upload files. 
Closing for now #wontfix

**Comment by edwbaker** [comment]
What do you mean by back-end in this case? There probably should be a way to do this for annotations.
