### ISSUE TITLE
Query views as databases instead of full download

### ISSUE THREAD

**Issue by qgeissmann** [BioAcoustica/bioacousticaR#9]
I am not sure what sort of scale we want to achieve for this project, but we may have a problem if we systematically download whole views. We may want to query views as remote databases instead...
This is really a  minor issue at the moment as the size of these view is negligible (compared to, say, one audio file)

**Comment by edwbaker** [comment]
This would open a set of issues about access rights - there are currently access restrictions implemented on some recordings, and the views handles access to these. It is possible to add dynamic filters to the views if this becomes necessary.

Views are essentially database queries, and can pretty much do whatever direct database access would allow. On top of that they deal with content access permissions, and if necessary in future we can cache them.
